const express=require('express');
const router=express.Router();
const blogController=require('../controllers/blogController');
const validateMiddleware=require('../middleware/validateMiddleware');
const { requireAuth } = require('../middleware/authMiddleware');
router.get('/',requireAuth,blogController.index);
router.post('/posts/store', requireAuth, validateMiddleware, blogController.store);
router.get('/post/:id',blogController.show);
router.get('/search',requireAuth,blogController.search);
router.get('/posts/new', requireAuth, blogController.create);
module.exports=router;